#!/usr/bin/env python3
"""View ideas generated by the loop.

Usage:
    python view_ideas.py              # show index summary
    python view_ideas.py --full       # show full text of every idea file
    python view_ideas.py --state      # show loop state
    python view_ideas.py --count      # just print the accepted idea count
"""

import argparse
import json
import os
from pathlib import Path


def show_state(state_file: str) -> None:
    if not os.path.exists(state_file):
        print("No state file found.")
        return
    with open(state_file) as f:
        state = json.load(f)
    print("Loop state:")
    for k, v in state.items():
        print(f"  {k}: {v}")
    print()


def show_index(index_file: str) -> None:
    if not os.path.exists(index_file):
        print(f"No index file found at {index_file}")
        return
    with open(index_file) as f:
        content = f.read()
    print(content)


def show_full(ideas_dir: str) -> None:
    idea_files = sorted(Path(ideas_dir).glob("idea_*.md"))
    if not idea_files:
        print(f"No idea files found in {ideas_dir}/")
        return
    print(f"{len(idea_files)} ideas\n")
    for path in idea_files:
        print("─" * 60)
        print(f"FILE: {path.name}")
        print("─" * 60)
        print(path.read_text())
        print()


def main():
    parser = argparse.ArgumentParser(description="View generated ideas")
    parser.add_argument("--index", default="ideas_index.md", help="Path to index file")
    parser.add_argument("--ideas-dir", default="ideas", help="Directory containing idea files")
    parser.add_argument("--state-file", default=".loop_state.json", help="Path to state file")
    parser.add_argument("--full", "-f", action="store_true", help="Show full text of every idea")
    parser.add_argument("--state", "-s", action="store_true", help="Show loop state")
    parser.add_argument("--count", "-n", action="store_true", help="Print idea count and exit")
    args = parser.parse_args()

    if args.count:
        idea_files = list(Path(args.ideas_dir).glob("idea_*.md"))
        print(len(idea_files))
        return

    if args.state:
        show_state(args.state_file)

    show_index(args.index)

    if args.full:
        show_full(args.ideas_dir)


if __name__ == "__main__":
    main()
